//! Build script for the karis-ky escrow contract.
//!
//! Captures build-time metadata (git commit, timestamp, package version) and
//! embeds it into the WASM artifact via two outputs:
//!
//! 1. `${OUT_DIR}/build_info.rs` — Rust source file with `pub const`s for
//!    `include!()` from `escrow/src/lib.rs`.
//! 2. `${CARGO_TARGET_DIR}/build_metadata.json` — JSON sidecar consumed by
//!    `scripts/validate_build_metadata.py` in CI.
//!
//! Also extracts `SCHEMA_VERSION` and `CONTRACT_INTERFACE_VERSION` from
//! `src/lib.rs` so the embedded values are guaranteed to match the source
//! of truth. Extraction failures are **loud** (panic with a clear message)
//! so the build fails visibly rather than silently embedding zeros.
//!
//! Git metadata failures default to a warning + `"unknown"` substitution.
//! Set `REQUIRE_GIT_METADATA=1` in the environment to make missing git
//! metadata a hard error — recommended for release builds.
//!
//! Rerun triggers:
//!   - `build.rs` itself
//!   - `src/lib.rs` (re-extract constants)
//!   - `.git/HEAD` and `.git/packed-refs` (re-capture commit hash)

use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by Cargo"),
    );
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by Cargo"));

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/lib.rs");

    let git_head = manifest_dir.join("../../.git/HEAD");
    if git_head.exists() {
        println!("cargo:rerun-if-changed={}", git_head.display());
    }
    let git_packed_refs = manifest_dir.join("../../.git/packed-refs");
    if git_packed_refs.exists() {
        println!("cargo:rerun-if-changed={}", git_packed_refs.display());
    }

    let require_git = std::env::var("REQUIRE_GIT_METADATA")
        .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
        .unwrap_or(false);

    let git_short = cmd_output(
        "git",
        &["rev-parse", "--short", "HEAD"],
        "unknown",
        require_git,
    );
    let git_full = cmd_output("git", &["rev-parse", "HEAD"], "unknown", require_git);
    let build_ts = cmd_output("date", &["-u", "+%Y-%m-%dT%H:%M:%SZ"], "unknown", false);
    let pkg_version = env!("CARGO_PKG_VERSION").to_string();
    let rust_version = cmd_output("rustc", &["--version"], "unknown", false);

    // Extract source-of-truth constants from `src/lib.rs`. These are load-bearing:
    // failing to extract them would silently embed zeros, breaking CI validation.
    let schema_version = extract_const(&manifest_dir.join("src/lib.rs"), "SCHEMA_VERSION")
        .unwrap_or_else(|| {
            panic!(
                "build.rs: failed to extract SCHEMA_VERSION from src/lib.rs. \
                 Expected format: `pub const SCHEMA_VERSION: u32 = <N>;`."
            )
        });
    let interface_version = extract_const(
        &manifest_dir.join("src/lib.rs"),
        "CONTRACT_INTERFACE_VERSION",
    )
    .unwrap_or_else(|| {
        panic!(
            "build.rs: failed to extract CONTRACT_INTERFACE_VERSION from src/lib.rs. \
                     Expected format: `pub const CONTRACT_INTERFACE_VERSION: u32 = <N>;`."
        )
    });

    // Generate Rust source file (consumed by `include!()` in lib.rs).
    let rs_content = format!(
        "// Auto-generated by build.rs — do not edit.\n\
         pub const BUILD_GIT_COMMIT: &str = \"{git_commit}\";\n\
         pub const BUILD_GIT_FULL_COMMIT: &str = \"{git_full}\";\n\
         pub const BUILD_TIMESTAMP: &str = \"{build_ts}\";\n\
         pub const BUILD_PKG_VERSION: &str = \"{pkg_version}\";\n\
         pub const BUILD_RUST_VERSION: &str = \"{rust_version}\";\n\
         pub const BUILD_SCHEMA_VERSION: u32 = {schema_version};\n\
         pub const BUILD_INTERFACE_VERSION: u32 = {interface_version};\n",
        git_commit = escape_str(&git_short),
        git_full = escape_str(&git_full),
        build_ts = escape_str(&build_ts),
        pkg_version = escape_str(&pkg_version),
        rust_version = escape_str(&rust_version),
        schema_version = schema_version,
        interface_version = interface_version,
    );
    std::fs::write(out_dir.join("build_info.rs"), rs_content).expect("write build_info.rs");

    // Generate JSON sidecar (consumed by `scripts/validate_build_metadata.py` in CI).
    let json_content = format!(
        "{{\n\
         \x20\"git_commit\": \"{git_commit}\",\n\
         \x20\"git_full_commit\": \"{git_full}\",\n\
         \x20\"build_timestamp\": \"{build_ts}\",\n\
         \x20\"pkg_version\": \"{pkg_version}\",\n\
         \x20\"rust_version\": \"{rust_version}\",\n\
         \x20\"schema_version\": {schema_version},\n\
         \x20\"interface_version\": {interface_version}\n\
         }}\n",
        git_commit = escape_str(&git_short),
        git_full = escape_str(&git_full),
        build_ts = escape_str(&build_ts),
        pkg_version = escape_str(&pkg_version),
        rust_version = escape_str(&rust_version),
        schema_version = schema_version,
        interface_version = interface_version,
    );

    let target_dir = std::env::var("CARGO_TARGET_DIR").unwrap_or_else(|_| "target".to_string());
    let json_path = Path::new(&target_dir).join("build_metadata.json");
    if let Some(parent) = json_path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    std::fs::write(&json_path, json_content)
        .unwrap_or_else(|e| panic!("write build_metadata.json to {}: {e}", json_path.display()));
}

/// Run a shell command and return its trimmed stdout, or `default` on failure.
///
/// When `require_ok` is `true` (driven by the `REQUIRE_GIT_METADATA` env var),
/// a non-zero exit or empty stdout **panics** instead of falling back to
/// `default`. Use this for git operations on release builds.
fn cmd_output(cmd: &str, args: &[&str], default: &str, require_ok: bool) -> String {
    match Command::new(cmd).args(args).output() {
        Ok(o) if o.status.success() => {
            let stdout = String::from_utf8_lossy(&o.stdout).trim().to_string();
            if stdout.is_empty() {
                if require_ok {
                    panic!(
                        "{cmd} {} returned empty stdout (REQUIRE_GIT_METADATA=1)",
                        args.join(" ")
                    );
                }
                return default.to_string();
            }
            stdout
        }
        Ok(_) => {
            if require_ok {
                panic!(
                    "{cmd} {} exited non-zero (REQUIRE_GIT_METADATA=1)",
                    args.join(" ")
                );
            }
            default.to_string()
        }
        Err(e) => {
            if require_ok {
                panic!("failed to spawn {cmd}: {e} (REQUIRE_GIT_METADATA=1)");
            }
            default.to_string()
        }
    }
}

/// Extract an integer constant from a Rust source file.
///
/// Looks for `pub const <NAME>: u32 = <value>;` and parses the value.
/// Returns `None` if the constant cannot be found or parsed.
fn extract_const(file: &Path, name: &str) -> Option<u32> {
    let content = std::fs::read_to_string(file).ok()?;
    let needle = format!("pub const {name}");
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with(&needle) {
            // Find the `=` and parse what follows.
            if let Some(after_eq) = trimmed.split('=').nth(1) {
                let value_str = after_eq.trim().trim_end_matches(';').trim();
                return value_str.parse().ok();
            }
        }
    }
    None
}

/// Escape a string for safe embedding in a Rust string literal.
fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
